name: 'Setup Tauri Build Environment'
description: 'Install dependencies needed for Tauri and Pipewire'

runs: 
  using: 'composite'
  steps:
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.6

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: install dependencies (ubuntu only)
      if: runner.os == 'Linux'
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libpipewire-0.3-dev

    - name: install frontend dependencies
      shell: sh
      run: bun install

    